Rails.configuration.app = 'ForSale'
Rails.configuration.app_name = 'ForSale WebApp'
Rails.configuration.app_flavor = 'ForSale'
Rails.configuration.app_flavor_subscript = ''
Rails.configuration.user = 'usuário'
Rails.configuration.email = ''
Rails.configuration.twitter = ''
Rails.configuration.avatar = 'avatar-m.png'
Rails.configuration.version = '4.5.2'
Rails.configuration.bs4v = '4.5'
Rails.configuration.logo = 'logo.png'
Rails.configuration.logo_m = 'logo.png'
Rails.configuration.copyright = '2021 © Samuel Barros'.html_safe
Rails.configuration.copyright_inverse = '2021 © Samuel Barros'.html_safe
Rails.configuration.icon_prefix = 'fal'
Rails.configuration.layout_settings = true
Rails.configuration.chat_interface = true
Rails.configuration.shortcut_menu = true
Rails.configuration.app_layout_shortcut = true
Rails.configuration.app_shortcut_modal = false
Rails.configuration.app_header = true
Rails.configuration.app_footer = true
Rails.configuration.app_sidebar = true
Rails.configuration.production_ready = false
Rails.configuration.google_analytics_id = ''
